version: '3.8'

services:
  # PostgreSQL Database
  database:
    image: postgres:15-alpine
    container_name: pana-inscriptions-db
    environment:
      POSTGRES_DB: pana-inscriptions-db
      POSTGRES_USER: pana-inscriptions-rw
      POSTGRES_PASSWORD: SuperSecretOMG
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pana-inscriptions-rw -d pana-inscriptions-db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend NestJS API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pana-inscriptions-backend
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://pana-inscriptions-rw:SuperSecretOMG@database:5432/pana-inscriptions-db
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      PORT: 3001
      FIG_API_URL: https://www.gymnastics.sport/api/athletes.php?function=searchLicenses&discipline=AER&country=&idlicense=&lastname=
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      database:
        condition: service_healthy
    command: npm run start:dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pana-inscriptions-frontend
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NEXT_PUBLIC_FIG_API_URL: https://www.gymnastics.sport/api/athletes.php?function=searchLicenses&discipline=AER&country=&idlicense=&lastname=
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    command: npm run dev

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: pana-inscriptions-network 