export interface Country {
  code: string; // IOC (International Olympic Committee) country code - used by FIG API
  name: string;
  flag: string;
}

export const countries: Country[] = [
  { code: "AFG", name: "Afghanistan", flag: "🇦🇫" },
  { code: "ALB", name: "Albania", flag: "🇦🇱" },
  { code: "ALG", name: "Algeria", flag: "🇩🇿" },
  { code: "ASA", name: "American Samoa", flag: "🇦🇸" },
  { code: "AND", name: "Andorra", flag: "🇦🇩" },
  { code: "ANG", name: "Angola", flag: "🇦🇴" },
  { code: "ANT", name: "Antigua and Barbuda", flag: "🇦🇬" },
  { code: "ARG", name: "Argentina", flag: "🇦🇷" },
  { code: "ARM", name: "Armenia", flag: "🇦🇲" },
  { code: "ARU", name: "Aruba", flag: "🇦🇼" },
  { code: "AUS", name: "Australia", flag: "🇦🇺" },
  { code: "AUT", name: "Austria", flag: "🇦🇹" },
  { code: "AZE", name: "Azerbaijan", flag: "🇦🇿" },
  { code: "BAH", name: "Bahamas", flag: "🇧🇸" },
  { code: "BRN", name: "Bahrain", flag: "🇧🇭" },
  { code: "BAN", name: "Bangladesh", flag: "🇧🇩" },
  { code: "BAR", name: "Barbados", flag: "🇧🇧" },
  { code: "BLR", name: "Belarus", flag: "🇧🇾" },
  { code: "BEL", name: "Belgium", flag: "🇧🇪" },
  { code: "BIZ", name: "Belize", flag: "🇧🇿" },
  { code: "BEN", name: "Benin", flag: "🇧🇯" },
  { code: "BER", name: "Bermuda", flag: "🇧🇲" },
  { code: "BHU", name: "Bhutan", flag: "🇧🇹" },
  { code: "BOL", name: "Bolivia", flag: "🇧🇴" },
  { code: "BIH", name: "Bosnia and Herzegovina", flag: "🇧🇦" },
  { code: "BOT", name: "Botswana", flag: "🇧🇼" },
  { code: "BRA", name: "Brazil", flag: "🇧🇷" },
  { code: "BRU", name: "Brunei", flag: "🇧🇳" },
  { code: "BUL", name: "Bulgaria", flag: "🇧🇬" },
  { code: "BUR", name: "Burkina Faso", flag: "🇧🇫" },
  { code: "BDI", name: "Burundi", flag: "🇧🇮" },
  { code: "CAM", name: "Cambodia", flag: "🇰🇭" },
  { code: "CMR", name: "Cameroon", flag: "🇨🇲" },
  { code: "CAN", name: "Canada", flag: "🇨🇦" },
  { code: "CPV", name: "Cape Verde", flag: "🇨🇻" },
  { code: "CAY", name: "Cayman Islands", flag: "🇰🇾" },
  { code: "CAF", name: "Central African Republic", flag: "🇨��" },
  { code: "CHA", name: "Chad", flag: "🇹🇩" },
  { code: "CHI", name: "Chile", flag: "🇨🇱" },
  { code: "CHN", name: "China", flag: "🇨🇳" },
  { code: "COL", name: "Colombia", flag: "🇨🇴" },
  { code: "COM", name: "Comoros", flag: "🇰🇲" },
  { code: "CGO", name: "Congo", flag: "🇨🇬" },
  { code: "COD", name: "Democratic Republic of the Congo", flag: "🇨🇩" },
  { code: "COK", name: "Cook Islands", flag: "🇨🇰" },
  { code: "CRC", name: "Costa Rica", flag: "🇨🇷" },
  { code: "CIV", name: "Côte d'Ivoire", flag: "🇨🇮" },
  { code: "CRO", name: "Croatia", flag: "🇭🇷" },
  { code: "CUB", name: "Cuba", flag: "🇨🇺" },
  { code: "CYP", name: "Cyprus", flag: "🇨🇾" },
  { code: "CZE", name: "Czech Republic", flag: "🇨🇿" },
  { code: "DEN", name: "Denmark", flag: "🇩🇰" },
  { code: "DJI", name: "Djibouti", flag: "🇩🇯" },
  { code: "DMA", name: "Dominica", flag: "🇩🇲" },
  { code: "DOM", name: "Dominican Republic", flag: "🇩🇴" },
  { code: "ECU", name: "Ecuador", flag: "🇪🇨" },
  { code: "EGY", name: "Egypt", flag: "🇪🇬" },
  { code: "ESA", name: "El Salvador", flag: "🇸🇻" },
  { code: "GEQ", name: "Equatorial Guinea", flag: "🇬🇶" },
  { code: "ERI", name: "Eritrea", flag: "🇪🇷" },
  { code: "EST", name: "Estonia", flag: "🇪🇪" },
  { code: "SWZ", name: "Eswatini", flag: "🇸🇿" },
  { code: "ETH", name: "Ethiopia", flag: "🇪🇹" },
  { code: "FIJ", name: "Fiji", flag: "🇫🇯" },
  { code: "FIN", name: "Finland", flag: "🇫🇮" },
  { code: "FRA", name: "France", flag: "🇫🇷" },
  { code: "GAB", name: "Gabon", flag: "🇬🇦" },
  { code: "GAM", name: "Gambia", flag: "🇬🇲" },
  { code: "GEO", name: "Georgia", flag: "🇬🇪" },
  { code: "GER", name: "Germany", flag: "🇩🇪" },
  { code: "GHA", name: "Ghana", flag: "🇬🇭" },
  { code: "GRE", name: "Greece", flag: "🇬🇷" },
  { code: "GRN", name: "Grenada", flag: "🇬🇩" },
  { code: "GUM", name: "Guam", flag: "🇬🇺" },
  { code: "GUA", name: "Guatemala", flag: "🇬🇹" },
  { code: "GUI", name: "Guinea", flag: "🇬🇳" },
  { code: "GBS", name: "Guinea-Bissau", flag: "🇬🇼" },
  { code: "GUY", name: "Guyana", flag: "🇬🇾" },
  { code: "HAI", name: "Haiti", flag: "🇭🇹" },
  { code: "HON", name: "Honduras", flag: "🇭🇳" },
  { code: "HKG", name: "Hong Kong", flag: "🇭🇰" },
  { code: "HUN", name: "Hungary", flag: "🇭🇺" },
  { code: "ISL", name: "Iceland", flag: "🇮🇸" },
  { code: "IND", name: "India", flag: "🇮🇳" },
  { code: "INA", name: "Indonesia", flag: "🇮🇩" },
  { code: "IRI", name: "Iran", flag: "🇮🇷" },
  { code: "IRQ", name: "Iraq", flag: "🇮🇶" },
  { code: "IRL", name: "Ireland", flag: "🇮🇪" },
  { code: "ISR", name: "Israel", flag: "🇮🇱" },
  { code: "ITA", name: "Italy", flag: "🇮🇹" },
  { code: "JAM", name: "Jamaica", flag: "🇯🇲" },
  { code: "JPN", name: "Japan", flag: "🇯🇵" },
  { code: "JOR", name: "Jordan", flag: "🇯🇴" },
  { code: "KAZ", name: "Kazakhstan", flag: "🇰🇿" },
  { code: "KEN", name: "Kenya", flag: "🇰🇪" },
  { code: "KIR", name: "Kiribati", flag: "🇰🇮" },
  { code: "PRK", name: "North Korea", flag: "🇰🇵" },
  { code: "KOR", name: "South Korea", flag: "🇰🇷" },
  { code: "KOS", name: "Kosovo", flag: "🇽🇰" },
  { code: "KUW", name: "Kuwait", flag: "🇰🇼" },
  { code: "KGZ", name: "Kyrgyzstan", flag: "🇰🇬" },
  { code: "LAO", name: "Laos", flag: "🇱🇦" },
  { code: "LAT", name: "Latvia", flag: "🇱🇻" },
  { code: "LBN", name: "Lebanon", flag: "🇱🇧" },
  { code: "LES", name: "Lesotho", flag: "🇱🇸" },
  { code: "LBR", name: "Liberia", flag: "🇱🇷" },
  { code: "LBA", name: "Libya", flag: "🇱🇾" },
  { code: "LIE", name: "Liechtenstein", flag: "🇱🇮" },
  { code: "LTU", name: "Lithuania", flag: "🇱🇹" },
  { code: "LUX", name: "Luxembourg", flag: "🇱🇺" },
  { code: "MAD", name: "Madagascar", flag: "🇲🇬" },
  { code: "MAW", name: "Malawi", flag: "🇲🇼" },
  { code: "MAS", name: "Malaysia", flag: "🇲🇾" },
  { code: "MDV", name: "Maldives", flag: "🇲🇻" },
  { code: "MLI", name: "Mali", flag: "🇲🇱" },
  { code: "MLT", name: "Malta", flag: "🇲🇹" },
  { code: "MHL", name: "Marshall Islands", flag: "🇲🇭" },
  { code: "MTN", name: "Mauritania", flag: "🇲🇷" },
  { code: "MRI", name: "Mauritius", flag: "🇲🇺" },
  { code: "MEX", name: "Mexico", flag: "🇲🇽" },
  { code: "FSM", name: "Micronesia", flag: "🇫🇲" },
  { code: "MDA", name: "Moldova", flag: "🇲🇩" },
  { code: "MON", name: "Monaco", flag: "🇲🇨" },
  { code: "MGL", name: "Mongolia", flag: "🇲🇳" },
  { code: "MNE", name: "Montenegro", flag: "🇲🇪" },
  { code: "MAR", name: "Morocco", flag: "🇲🇦" },
  { code: "MOZ", name: "Mozambique", flag: "🇲🇿" },
  { code: "MYA", name: "Myanmar", flag: "🇲🇲" },
  { code: "NAM", name: "Namibia", flag: "🇳🇦" },
  { code: "NRU", name: "Nauru", flag: "🇳🇷" },
  { code: "NEP", name: "Nepal", flag: "🇳🇵" },
  { code: "NED", name: "Netherlands", flag: "🇳🇱" },
  { code: "NZL", name: "New Zealand", flag: "🇳🇿" },
  { code: "NCA", name: "Nicaragua", flag: "🇳🇮" },
  { code: "NIG", name: "Niger", flag: "🇳🇪" },
  { code: "NGR", name: "Nigeria", flag: "🇳🇬" },
  { code: "MKD", name: "North Macedonia", flag: "🇲🇰" },
  { code: "NOR", name: "Norway", flag: "🇳🇴" },
  { code: "OMA", name: "Oman", flag: "🇴🇲" },
  { code: "PAK", name: "Pakistan", flag: "🇵🇰" },
  { code: "PLW", name: "Palau", flag: "🇵🇼" },
  { code: "PLE", name: "Palestine", flag: "🇵🇸" },
  { code: "PAN", name: "Panama", flag: "🇵🇦" },
  { code: "PNG", name: "Papua New Guinea", flag: "🇵🇬" },
  { code: "PAR", name: "Paraguay", flag: "🇵🇾" },
  { code: "PER", name: "Peru", flag: "🇵🇪" },
  { code: "PHI", name: "Philippines", flag: "🇵🇭" },
  { code: "POL", name: "Poland", flag: "🇵🇱" },
  { code: "POR", name: "Portugal", flag: "🇵🇹" },
  { code: "PUR", name: "Puerto Rico", flag: "🇵🇷" },
  { code: "QAT", name: "Qatar", flag: "🇶🇦" },
  { code: "ROU", name: "Romania", flag: "🇷🇴" },
  { code: "RUS", name: "Russia", flag: "🇷🇺" },
  { code: "RWA", name: "Rwanda", flag: "🇷🇼" },
  { code: "SKN", name: "Saint Kitts and Nevis", flag: "🇰🇳" },
  { code: "LCA", name: "Saint Lucia", flag: "🇱🇨" },
  { code: "VIN", name: "Saint Vincent and the Grenadines", flag: "🇻🇨" },
  { code: "SAM", name: "Samoa", flag: "🇼🇸" },
  { code: "SMR", name: "San Marino", flag: "🇸🇲" },
  { code: "STP", name: "São Tomé and Príncipe", flag: "🇸🇹" },
  { code: "KSA", name: "Saudi Arabia", flag: "🇸🇦" },
  { code: "SEN", name: "Senegal", flag: "🇸🇳" },
  { code: "SRB", name: "Serbia", flag: "🇷🇸" },
  { code: "SEY", name: "Seychelles", flag: "🇸🇨" },
  { code: "SLE", name: "Sierra Leone", flag: "🇸🇱" },
  { code: "SIN", name: "Singapore", flag: "🇸🇬" },
  { code: "SVK", name: "Slovakia", flag: "🇸🇰" },
  { code: "SLO", name: "Slovenia", flag: "🇸🇮" },
  { code: "SOL", name: "Solomon Islands", flag: "🇸🇧" },
  { code: "SOM", name: "Somalia", flag: "🇸🇴" },
  { code: "RSA", name: "South Africa", flag: "🇿🇦" },
  { code: "SSD", name: "South Sudan", flag: "🇸🇸" },
  { code: "ESP", name: "Spain", flag: "🇪🇸" },
  { code: "SRI", name: "Sri Lanka", flag: "🇱🇰" },
  { code: "SUD", name: "Sudan", flag: "🇸🇩" },
  { code: "SUR", name: "Suriname", flag: "🇸🇷" },
  { code: "SWE", name: "Sweden", flag: "🇸🇪" },
  { code: "SUI", name: "Switzerland", flag: "🇨🇭" },
  { code: "SYR", name: "Syria", flag: "🇸🇾" },
  { code: "TPE", name: "Taiwan", flag: "🇹🇼" },
  { code: "TJK", name: "Tajikistan", flag: "🇹🇯" },
  { code: "TAN", name: "Tanzania", flag: "🇹🇿" },
  { code: "THA", name: "Thailand", flag: "🇹🇭" },
  { code: "TLS", name: "Timor-Leste", flag: "🇹🇱" },
  { code: "TOG", name: "Togo", flag: "🇹🇬" },
  { code: "TGA", name: "Tonga", flag: "🇹🇴" },
  { code: "TTO", name: "Trinidad and Tobago", flag: "🇹🇹" },
  { code: "TUN", name: "Tunisia", flag: "🇹🇳" },
  { code: "TUR", name: "Turkey", flag: "🇹🇷" },
  { code: "TKM", name: "Turkmenistan", flag: "🇹🇲" },
  { code: "TUV", name: "Tuvalu", flag: "🇹🇻" },
  { code: "UGA", name: "Uganda", flag: "🇺🇬" },
  { code: "UKR", name: "Ukraine", flag: "🇺🇦" },
  { code: "UAE", name: "United Arab Emirates", flag: "🇦🇪" },
  { code: "GBR", name: "United Kingdom", flag: "🇬🇧" },
  { code: "USA", name: "United States", flag: "🇺🇸" },
  { code: "URU", name: "Uruguay", flag: "🇺🇾" },
  { code: "UZB", name: "Uzbekistan", flag: "🇺🇿" },
  { code: "VAN", name: "Vanuatu", flag: "🇻🇺" },
  { code: "VEN", name: "Venezuela", flag: "🇻🇪" },
  { code: "VIE", name: "Vietnam", flag: "🇻🇳" },
  { code: "ISV", name: "US Virgin Islands", flag: "🇻🇮" },
  { code: "IVB", name: "British Virgin Islands", flag: "🇻🇬" },
  { code: "YEM", name: "Yemen", flag: "🇾🇪" },
  { code: "ZAM", name: "Zambia", flag: "🇿🇲" },
  { code: "ZIM", name: "Zimbabwe", flag: "🇿🇼" }
];

// Popular countries for Panamerican Championships (using IOC codes)
export const popularCountries: Country[] = [
  // North America
  { code: "USA", name: "United States", flag: "🇺🇸" },
  { code: "CAN", name: "Canada", flag: "🇨🇦" },
  { code: "MEX", name: "Mexico", flag: "🇲🇽" },
  
  // Central America & Caribbean
  { code: "CRC", name: "Costa Rica", flag: "🇨🇷" },
  { code: "CUB", name: "Cuba", flag: "🇨🇺" },
  { code: "DOM", name: "Dominican Republic", flag: "🇩🇴" },
  { code: "GUA", name: "Guatemala", flag: "🇬🇹" },
  { code: "JAM", name: "Jamaica", flag: "🇯🇲" },
  { code: "PAN", name: "Panama", flag: "🇵🇦" },
  { code: "PUR", name: "Puerto Rico", flag: "🇵🇷" },
  { code: "TTO", name: "Trinidad and Tobago", flag: "🇹🇹" },
  
  // South America
  { code: "ARG", name: "Argentina", flag: "🇦🇷" },
  { code: "BOL", name: "Bolivia", flag: "🇧🇴" },
  { code: "BRA", name: "Brazil", flag: "🇧🇷" },
  { code: "CHI", name: "Chile", flag: "🇨🇱" },
  { code: "COL", name: "Colombia", flag: "🇨🇴" },
  { code: "ECU", name: "Ecuador", flag: "🇪🇨" },
  { code: "PER", name: "Peru", flag: "🇵🇪" },
  { code: "URU", name: "Uruguay", flag: "🇺🇾" },
  { code: "VEN", name: "Venezuela", flag: "🇻🇪" },
  
  // Other major gymnastics countries
  { code: "ESP", name: "Spain", flag: "🇪🇸" },
  { code: "FRA", name: "France", flag: "🇫🇷" },
  { code: "GER", name: "Germany", flag: "🇩🇪" },
  { code: "GBR", name: "United Kingdom", flag: "🇬🇧" },
  { code: "ITA", name: "Italy", flag: "🇮🇹" },
  { code: "RUS", name: "Russia", flag: "🇷🇺" },
  { code: "CHN", name: "China", flag: "🇨🇳" },
  { code: "JPN", name: "Japan", flag: "🇯🇵" },
  { code: "AUS", name: "Australia", flag: "🇦🇺" }
];

// Helper function to get country by code
export function getCountryByCode(code: string): Country | undefined {
  return countries.find(country => country.code === code);
}

// Helper function to get country flag by code (backwards compatibility)
export function getCountryFlag(code: string): string {
  const country = getCountryByCode(code);
  return country?.flag || '🏳️';
}

// Popular countries for quick access (Americas first for Panamerican Championship)
export const POPULAR_COUNTRIES = [
  // North America
  'USA', 'CAN', 'MEX',
  // Central America & Caribbean
  'CRC', 'CUB', 'DOM', 'GUA', 'JAM', 'PAN', 'PUR', 'TTO',
  // South America
  'ARG', 'BOL', 'BRA', 'CHI', 'COL', 'ECU', 'PER', 'URU', 'VEN',
  // Other major gymnastics countries
  'ESP', 'FRA', 'GER', 'GBR', 'ITA', 'RUS', 'CHN', 'JPN', 'AUS'
].map(code => countries.find(c => c.code === code)!).filter(Boolean); 